version: 2
jobs:
  build:
    working_directory: ~/rollup-plugin-just-gzip
    docker:
      - image: circleci/node:8
        environment:
          FOOBIEX: "barry"
    steps:
      - checkout
      - restore_cache:
          keys:
          - rollup-plugin-just-gzip-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - rollup-plugin-just-gzip-
      - run:
          name: Installing dependencies
          command: yarn install
          when: always
      - save_cache:
          key: rollup-plugin-just-gzip-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Running tests
          command: yarn test
          when: on_success
      - run:
          name: Custom
          command: echo $FOOBIEX
          when: always
      - run:
          name: Uploading test coverage
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
