version: 2
jobs:
  build:
    working_directory: ~/rollup-plugin-just-gzip
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - rollup-plugin-just-gzip-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - rollup-plugin-just-gzip-fallback-
      - run:
          name: Installing dependencies
          command: yarn install
          when: always
      - save_cache:
          key: rollup-plugin-just-gzip-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Building and testing the project
          command: yarn test
          when: on_success
      - run:
          name: Sending test coverage to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
workflows:
  version: 2
  # Runs on 12am UTC every day
  # to check is the master is stable
  stability:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
